GAMMA: float = 1.0

# ALPHA: float = 0.9
INITIAL_V_VALUE: float = 0.0
INITIAL_Q_VALUE: float = 0.0

TRAINING_ITERATIONS: int = 100
EPISODE_LENGTH_TIMEOUT: int = 100

PERFORMANCE_SAMPLE_START: int = 0
PERFORMANCE_SAMPLE_FREQUENCY: int = 1

RUNS: int = 10
# TESTS: int = 100
MOVING_AVERAGE_WINDOW_SIZE = 19
