GAMMA: float = 1.0

ALPHA: float = 0.1
INITIAL_Q_VALUE: float = 0.0
# for deletion
EXTRA_REWARD_FOR_FAILURE: float = 0.0
SKID_PROBABILITY: float = 0.0

TRAINING_ITERATIONS: int = 500
EPISODE_LENGTH_TIMEOUT: int = 100

PERFORMANCE_SAMPLE_START: int = 0
PERFORMANCE_SAMPLE_FREQUENCY: int = 1
PERFORMANCE_SAMPLES: int = 500

RUNS: int = 100
TESTS: int = 100
MOVING_AVERAGE_WINDOW_SIZE = 19
